language: node_js
node_js:
- stable
script: bash ./scripts/deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: Build gh-pages
  - COMMIT_AUTHOR_EMAIL: ht@thanhtunguet.info
before_install:
- openssl aes-256-cbc -K $encrypted_bee6121212f1_key -iv $encrypted_bee6121212f1_iv
  -in deploy_key.enc -out deploy_key -d
