// Type declaration generated by http://www.json2ts.com

declare module 'teko-product-discovery' {
  export interface Seller {
    id?: number;

    name?: string;

    displayName?: string;
  }

  export interface Brand {
    code?: string;

    name?: string;
  }

  export interface Status {
    publish?: boolean;

    sale?: string;
  }

  export interface Objective {
    code?: string;

    name?: string;
  }

  export interface ProductType {
    code?: string;

    name?: string;
  }

  export interface Image {
    url?: string;

    priority?: number;

    path?: string;
  }

  export interface ProductLine {
    code?: string;

    name?: string;
  }

  export interface ParentBundle {
    sku?: string;

    name?: string;

    displayName?: any;
  }

  export interface TotalAvailableByStock {
    type?: string;

    total?: number;
  }

  export interface Color {
    code?: string;

    name?: string;
  }

  export interface PromotionPrice {
    channel?: string;

    terminal?: string;

    finalPrice?: number;

    promotionPrice?: any;

    bestPrice?: number;

    flashSalePrice?: any;
  }

  export interface Condition {
    paymentMethods?: string[];

    orderValueMin?: any;

    orderValueMax?: any;

    coupon?: string;

    blockSize?: number;

    minQuantity?: number;
  }

  export interface Money {
    id?: number;

    money?: number;

    percent?: any;

    maxDiscount?: any;

    discountType?: string;

    budgetId?: number;

    budgetStatus?: string;

    outOfBudget?: boolean;

    maxDiscountPerOrder?: any;
  }

  export interface Benefit2 {
    money?: Money[];

    items?: any[];
  }

  export interface AppliedPromotion {
    id?: number;

    name?: string;

    description?: string;

    benefit?: Benefit2;
  }

  export interface Voucher {
    quantity?: number;

    maxQuantity?: number;

    budgetStatus?: string;

    outOfBudget?: boolean;

    appliedPromotion?: AppliedPromotion;
  }

  export interface Money2 {
    id?: number;

    money?: number;

    percent?: any;

    maxDiscount?: any;

    discountType?: string;

    budgetId?: number;

    budgetStatus?: string;

    outOfBudget?: boolean;

    maxDiscountPerOrder?: any;
  }

  export interface Item {
    id?: number;

    sku?: string;

    name?: string;

    quantity?: number;

    budgetId?: number;

    budgetStatus?: string;

    outOfBudget?: boolean;

    maxQuantityPerOrder?: any;
  }

  export interface Benefit {
    voucher?: Voucher;

    money?: Money2[];

    items?: Item[];
  }

  export interface Definition {
    id?: number;

    startedAt?: Date;

    endedAt?: Date;

    name?: string;

    govRegister?: boolean;

    type?: string;

    isDefault?: boolean;

    partner?: string;

    description?: string;

    timeRanges?: any[];

    condition?: Condition;

    applyOn?: string;

    benefit?: Benefit;
  }

  export interface Promotion {
    channel?: string;

    terminal?: string;

    definitions?: Definition[];
  }

  export interface AttributeSet {
    id?: number;

    name?: string;
  }

  export interface Category {
    id?: number;

    code?: string;

    name?: string;

    level?: number;

    parentId?: number;
  }

  export interface SeoInfo {
    metaKeyword?: any;

    metaTitle?: any;

    metaDescription?: any;

    shortDescription?: string;

    description?: any;
  }

  export interface Rating {
    averagePoint?: number;

    voteCount?: number;
  }

  export interface Result {
    products?: Product[];

    product?: Product;

    keywords?: any[];

    filters?: any[];
  }

  export interface PriceRange {
    maxPrice?: number;

    minPrice?: number;
  }

  export interface Extra {
    totalItems?: number;

    page?: number;

    pageSize?: number;

    priceRanges?: PriceRange[];
  }

  export interface RootObject {
    code?: string;

    result?: Result;

    extra?: Extra;
  }

  export interface Seller {
    id?: number;

    name?: string;

    displayName?: string;
  }

  export interface Brand {
    code?: string;

    name?: string;
  }

  export interface Status {
    publish?: boolean;

    sale?: string;
  }

  export interface Objective {
    code?: string;

    name?: string;
  }

  export interface ProductType {
    code?: string;

    name?: string;
  }

  export interface Image {
    url?: string;

    priority?: number;

    path?: string;
  }

  export interface ProductLine {
    code?: string;

    name?: string;
  }

  export interface Color {
    code?: any;

    name?: any;
  }

  export interface AttributeSet {
    id?: number;

    name?: string;
  }

  export interface Category {
    id?: number;

    code?: string;

    name?: string;

    level?: number;

    parentId?: number;
  }

  export interface SeoInfo {
    metaKeyword?: string;

    metaTitle?: string;

    metaDescription?: string;

    shortDescription?: string;

    description?: string;
  }

  export interface Rating {
    averagePoint?: number;

    voteCount?: number;
  }

  export interface Value {
    optionId?: number;

    value?: string;
  }

  export interface Attribute {
    code?: string;

    values?: Value[];
  }

  export interface SaleCategory {
    id?: number;

    path?: string;

    name?: string;

    url?: string;
  }

  export interface AttributeGroup {
    id?: number;

    name?: string;

    value?: string;

    parentId?: number;

    priority?: number;
  }

  export interface Warranty {
    months?: number;

    description?: any;
  }

  export interface Seller {
    id?: number;

    name?: string;

    displayName?: string;
  }

  export interface Brand {
    code?: string;

    name?: string;
  }

  export interface Status {
    publish?: boolean;

    sale?: string;
  }

  export interface Objective {
    code?: string;

    name?: string;
  }

  export interface ProductType {
    code?: string;

    name?: string;
  }

  export interface Image {
    url?: string;

    priority?: number;

    path?: string;
  }

  export interface Price {
    supplierSalePrice?: number;

    sellPrice?: number;
  }

  export interface ProductLine {
    code?: string;

    name?: string;
  }

  export interface TotalAvailableByStock {
    type?: string;

    total?: number;
  }

  export interface Color {
    code?: any;

    name?: any;
  }

  export interface AttributeSet {
    id?: number;

    name?: string;
  }

  export interface Category {
    id?: number;

    code?: string;

    name?: string;

    level?: number;

    parentId?: number;
  }

  export interface SeoInfo {
    metaKeyword?: string;

    metaTitle?: string;

    metaDescription?: string;

    shortDescription?: string;

    description?: string;
  }

  export interface Rating {
    averagePoint?: any;

    voteCount?: number;
  }

  export interface Value {
    optionId?: number;

    value?: string;
  }

  export interface Attribute {
    code?: string;

    values?: Value[];
  }

  export interface SaleCategory {
    id?: number;

    path?: string;

    name?: string;

    url?: string;
  }

  export interface AttributeGroup {
    id?: number;

    name?: string;

    value?: string;

    parentId?: number;

    priority?: number;
  }

  export interface Warranty {
    months?: number;

    description?: any;
  }

  export interface Product {
    sku?: string;

    name?: string;

    url?: string;

    seller?: Seller;

    brand?: Brand;

    status?: Status;

    objective?: Objective;

    productType?: ProductType;

    images?: Image[];

    price?: Price;

    productLine?: ProductLine;

    stocks?: any[];

    totalAvailable?: number;

    isBundle?: boolean;

    bundleProducts?: any;

    parentBundles?: ParentBundle[];

    totalAvailableByStocks?: TotalAvailableByStock[];

    displayName?: string;

    color?: Color;

    tags?: any[];

    promotionPrices?: PromotionPrice[];

    promotions?: Promotion[];

    flashSales?: any[];

    attributeSet?: AttributeSet;

    categories?: Category[];

    magentoId?: number;

    seoInfo?: SeoInfo;

    rating?: Rating;

    allActiveFlashSales?: any[];

    sku?: string;

    name?: string;

    url?: string;

    seller?: Seller;

    brand?: Brand;

    status?: Status;

    objective?: Objective;

    productType?: ProductType;

    images?: Image[];

    price?: Price;

    productLine?: ProductLine;

    stocks?: any[];

    totalAvailable?: number;

    isBundle?: boolean;

    bundleProducts?: any;

    parentBundles?: any;

    totalAvailableByStocks?: any[];

    displayName?: string;

    color?: Color;

    tags?: any[];

    promotionPrices?: any[];

    promotions?: any[];

    flashSales?: any[];

    attributeSet?: AttributeSet;

    categories?: Category[];

    magentoId?: number;

    seoInfo?: SeoInfo;

    rating?: Rating;

    allActiveFlashSales?: any[];

    productGroup?: any;

    attributes?: Attribute[];

    saleCategories?: SaleCategory[];

    taxOut?: number;

    taxOutCode?: string;

    attributeGroups?: AttributeGroup[];

    warranty?: Warranty;

    createdAt?: Date;

    salePoint?: number;

    importPrice?: any;

    recommendMethod?: any;

    sku?: string;

    name?: string;

    url?: string;

    seller?: Seller;

    brand?: Brand;

    status?: Status;

    objective?: Objective;

    productType?: ProductType;

    images?: Image[];

    price?: Price;

    productLine?: ProductLine;

    stocks?: any[];

    totalAvailable?: number;

    isBundle?: boolean;

    bundleProducts?: any;

    parentBundles?: any;

    totalAvailableByStocks?: TotalAvailableByStock[];

    displayName?: string;

    color?: Color;

    tags?: any[];

    promotionPrices?: any[];

    promotions?: any[];

    flashSales?: any[];

    attributeSet?: AttributeSet;

    categories?: Category[];

    magentoId?: number;

    seoInfo?: SeoInfo;

    rating?: Rating;

    allActiveFlashSales?: any[];

    productGroup?: any;

    attributes?: Attribute[];

    saleCategories?: SaleCategory[];

    taxOut?: number;

    taxOutCode?: string;

    attributeGroups?: AttributeGroup[];

    warranty?: Warranty;

    createdAt?: Date;

    salePoint?: number;

    importPrice?: any;

    recommendMethod?: any;
  }



  export interface RootObject {
    code?: string;

    result?: Result;
  }
}
